name: Publish CLDP Pages

on:
  push:
    paths:
      - 'Translated/**/*.*'
      - 'Claimed/**/*.*'
  workflow_dispatch:

jobs:
  documents-build:

    runs-on: ubuntu-latest

    steps:
    - name: Building System Preparation 
      run: |
        sudo apt update
        sudo apt -y install texlive-font-utils linuxdoc-tools-text linuxdoc-tools-latex docbook-dsssl docbook-xsl docbook-utils htmldoc htmldoc-common docbook-xsl html2text docbook5-xml docbook-xsl-ns jing asciidoc libxml2-utils python3-stdeb fakeroot python3-all python3-networkx python3-nose fop ldp-docbook-xsl ldp-docbook-dsssl docbook opensp dh-python
      shell: bash

    - name: Restoring Martins LDP Python Scripts from Cache
      id: pythontldp
      uses: actions/cache@v1
      with:
        path: ~/work/python-tldp/deb_dist
        key: ${{ runner.os }}-pythontldp

    - name: Compiling Martins LDP Python Scripts if not Found in Cache
      if: steps.pythontldp.outputs.cache-hit != 'true'
      run: |
        cd ~/work
        git clone https://github.com/tLDP/python-tldp
        cd python-tldp && rm -rf debian
        python3 setup.py --command-packages=stdeb.command bdist_deb
      shell: bash

    - name: Installation of Martins LDP Python Scripts
      run: |
        cd ~/work
        sudo dpkg -i python-tldp/deb_dist/python3-tldp_*_all.deb
        ldptool --dump-cfg
      shell: bash

    - name: Checkout CLDP
      uses: actions/checkout@v2
      with:
        path: CLDP
        ref: master
        persist-credentials: false

    - name: Check LDP
      run: |
        cd /home/runner/work/CLDP/CLDP/CLDP
        git clone https://github.com/tLDP/LDP LDP
      shell: bash
        
    - name: Checkout CLDPP
      uses: actions/checkout@v2
      with:
        repository: Starryi/CLDPP
        path: CLDPP
        ref: master
        ssh-key: ${{ secrets.SSHK }}

    - name: LDP Documents Processing via Martins scripts
      run: |
        cd /home/runner/work/CLDP/CLDP/CLDP/.github
        ldptool --configfile guide.builder.ldptool.cfg
        ldptool --configfile ref.builder.ldptool.cfg
        ldptool --configfile guide.builder.ldptool.cfg
        ldptool --configfile howto.builder.ldptool.cfg
      shell: bash
    
    - name: Build index html
      uses: actions/setup-node@v1
    - run: |
        cd /home/runner/work/CLDP/CLDP/CLDP/.github
        node build_index.js

    - name: Built Documents Transfer for Master Main Documents
      run: |
        cd ~/work/CLDP/CLDP/CLDPP
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "generated"
        git push -u origin master
      shell: bash
